.TH PTYXIS-TAB-COLORS 1 "October 2026" "Ptyxis-TC 50.2" "User Commands"
.SH NAME
ptyxis-tab-colors \- terminal with hostname tab colors
.SH SYNOPSIS
.B ptyxis-tab-colors
.RI [ options ]
.SH DESCRIPTION
Launches the custom Ptyxis terminal with a separate application and settings
identity. Right-click copies selected text or pastes when no text is selected.
Shift plus right-click opens the context menu.
.SH OPTIONS
Use
.B --help
for the underlying Ptyxis command options.
.SH FILES
.I ~/.config/org.gnome.Ptyxis.TabColors/tab-colors.ini
contains hostname and alias color mappings. An example is installed in
.I /usr/share/doc/ptyxis-tc/tab-colors.ini.
.SH AUTHOR
Ptyxis is developed by Christian Hergert and contributors.
Ptyxis-TC modifications are by Bob Czys.
